/* eslint-disable react/function-component-definition */
import { ToastContainer } from 'react-toastify';
import ClientLayout from './clientLayout';
import ServerRootLayout from './serverLayout';
import 'react-toastify/dist/ReactToastify.css';

export const metadata = {
  title: process.env.NEXT_PUBLIC_BRAND_NAME,
  description: 'Generated by create next app',
};

export default function Layout({ children }) {
  return (
    <ServerRootLayout>
      <ClientLayout>
        <ToastContainer />
        {children}
      </ClientLayout>
    </ServerRootLayout>
  );
}
